@URL = http://localhost:8080/auth

// ==================================================
// ====================== POST ======================
// ==================================================
###Cadastrar uma autenticação
POST {{URL}}
Content-Type: application/json

{
    "username": "conti2@email.com",
    "password": "conti1234"
}