@URL = http://localhost:8080/auth

// ==================================================
// ====================== POST ======================
// ==================================================
###Cadastrar uma autenticação
POST {{URL}}
Content-Type: application/json

{
    "username": "email@email.com",
    "password": "12341234"
}