@URL_BASE=http://localhost:8080
// ==================================================
// ====================== POST ======================
// ==================================================
###Cadastrar um pacote
POST {{URL_BASE}}/pacote
Content-Type: application/json

{
    "nome": "Pacote Épico da Aventura Espacial",
    "descricao": "Prepare-se para a viagem mais estranha e emocionante da sua vida.",
    "valor": 999999.99,
    "duracaoEmDias": 7,
    "dataInicio": "2024-04-01",
    "dataFim": "2024-04-07"
}
###Cadastrar um pacote
POST {{URL_BASE}}/pacote
Content-Type: application/json

{
    "nome": "Exploração Extrema das Cataratas do Iguaçu",
    "descricao": "Prepare-se para uma aventura aquática como nenhuma outra!",
    "valor": 2499.99,
    "duracaoEmDias": 5,
    "dataInicio": "2023-11-15",
    "dataFim": "2023-11-19"
}

// ==================================================
// ====================== GET =======================
// ==================================================
###Obter todos os pacotes por pagina
GET {{URL_BASE}}/pacote/pages?size=20&page=2&direction=DESC

###Obter todos os pacotes
GET {{URL_BASE}}/pacote

###Obter pacote pelo ID
GET {{URL_BASE}}/pacote/7dfcb6aa-9ef0-4fa1-b725-2a91edca43c7

// ==================================================
// ====================== PUT =======================
// ==================================================
### Atualizar 1 pacote
PUT {{URL_BASE}}/pacote/7dfcb6aa-9ef0-4fa1-b725-2a91edca43c7
Content-Type: application/json

{
    "nome": "Alterado",
    "descricao": "Alterado!",
    "valor": 2499.99,
    "duracaoEmDias": 5,
    "dataInicio": "2023-11-15",
    "dataFim": "2023-11-19"
}

// ==================================================
// ===================== DELETE =====================
// ==================================================
### Deletar pacote pelo id
DELETE {{URL_BASE}}/pacote/7dfcb6aa-9ef0-4fa1-b725-2a91edca43c7