@URL_BASE=http://localhost:8080
### create
POST {{URL_BASE}}/pagamento
Content-Type: application/json

{
    "formaPagamento": "Crédito"
}
### getAll
GET {{URL_BASE}}/pagamento
### getById
GET {{URL_BASE}}/pagamento/0a8dcd94-275e-4224-a9c3-ee86915358bc
###
PUT {{URL_BASE}}/pagamento/9878a38e-fdfd-406e-91e5-0f6865199c61
Content-Type: application/json

{
    "formaPagamento": "Créditobb"
}
###
DELETE {{URL_BASE}}/pagamento/9878a38e-fdfd-406e-91e5-0f6865199c61