@URL_BASE=http://localhost:8080

// ------------------ GET ------------------
###Obter todos os pagamentos por pagina
GET {{URL_BASE}}/pagamento/pages?size=20&page=2&sort=email&direction=DESC

###Obter todos os pagamentos
GET {{URL_BASE}}/pagamento

###Obter pagamento pelo ID
GET {{URL_BASE}}/pagamento/10


// ------------------ PUT ------------------




// ------------------ POST ------------------
###Cadastrar um pagamento
POST {{URL_BASE}}/pagamento
Content-Type: application/json

{
    "valor": 555.44,
    "formaPagamento" : "cartãoCrédito",
}




// ------------------ DELETE ------------------