@URL_BASE=http://localhost:8080


### Create
POST {{URL_BASE}}/passeio
Content-Type: application/json

{
    "nome": "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
    "descricao": "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
    "valor": 55,
    "duracaoEmHoras": 5,  
    "vagasDisponiveis": "2",
    "classificacao": "12"
}

### GetAll
GET {{URL_BASE}}/passeio

### GetById
GET {{URL_BASE}}/passeio/4b624124-5e6d-444f-bf36-c1a42da223fe

### Put
PUT {{URL_BASE}}/passeio/4b624124-5e6d-444f-bf36-c1a42da223fe
Content-Type: application/json

{
    "nome": "bbbbbbbbbbbbbbbbbbbbbbbbbb",
    "descricao": "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
    "valor": 55,
    "duracaoEmHoras": 5,  
    "vagasDisponiveis": "2",
    "classificacao": "12"
}

### Delete
DELETE {{URL_BASE}}/passeio/4b624124-5e6d-444f-bf36-c1a42da223fe