@URL_BASE=http://localhost:8080
### create
POST {{URL_BASE}}/person
Content-Type: application/json

{
    "nome": "aaaaaaaaaaaaaaa",
    "email": "aas123232sa@hsshh.com",
    "senha": "12346123123",
    "telefone": "12341231236",  
    "nascimento": "2001-11-11",
    "perfil": "Cliente"
}
### getAll
GET {{URL_BASE}}/person
### getById
GET {{URL_BASE}}/person/d21dbf14-3b4a-439b-8463-286d1b8e0865
###
PUT {{URL_BASE}}/person/d21dbf14-3b4a-439b-8463-286d1b8e0865
Content-Type: application/json

{
    "nome": "114fawer2134",
    "email": "aassa@hsshh.com",
    "senha": "12346123123",
    "telefone": "12341231236",  
    "nascimento": "2001-11-11",
    "perfil": "Cliente"
}
###
DELETE {{URL_BASE}}/person/d21dbf14-3b4a-439b-8463-286d1b8e0865