@URL_BASE=http://localhost:8080
### create
POST {{URL_BASE}}/pacote
Content-Type: application/json

{
    "nome": "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
    "descricao": "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
    "valor": 55,
    "duracaoEmDias": 5,  
    "dataInicio": "2023-11-11",
    "dataFim": "2024-01-01",
    "vagasDisponiveis": "3"
}
### getAll
GET {{URL_BASE}}/pacote
### getById
GET {{URL_BASE}}/pacote/e91795f0-740c-4b5e-a110-fab8a98a233b
###
PUT {{URL_BASE}}/pacote/e91795f0-740c-4b5e-a110-fab8a98a233b
Content-Type: application/json

{
    "nome": "bbbbbbbbaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
    "descricao": "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
    "valor": 55,
    "duracaoEmDias": 5,  
    "dataInicio": "2023-11-11",
    "dataFim": "2024-01-01",
    "vagasDisponiveis": "3"
}
###
DELETE {{URL_BASE}}/pacote/4e6ec364-fd01-434d-b4ef-4d9fb232e070