@URL = http://localhost:8080

@token = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJBUEkgYXV0aGVudGljYXRpb24iLCJpZCI6IjM4MGM4NGUzLTVlYjktNDI5NS1hOTAxLTdhZDMwOGE5ZTcxYiIsInVzZXJuYW1lIjoidXN1YXJpb0BlbWFpbC5jb20iLCJpYXQiOjE2OTg0MDg2NjcsImV4cCI6MTY5ODQxMjI2NywiaXNzIjoiVVRGUFIifQ.fnz9ys9J1SOM2EviJiNwSlKAoaEfYrgL25VHDqFIfME

### Create 
POST {{URL}}/person
Content-Type: application/json

{
    "name": "usuario",
    "email": "usuario@email.com",
    "password": "12341234",
    "phone": "123443211234",  
    "birth": "2001-11-11",
    "profile": "Cliente"
}

### GetAll
GET {{URL}}/person
Authorization: {{token}}

### GetById
GET {{URL}}/person/0b6f2aa9-6923-42bb-b3e7-e6e1b3b1095f
Authorization: {{token}}
 
### Put
PUT {{URL}}/person/0b6f2aa9-6923-42bb-b3e7-e6e1b3b1095f
Content-Type: application/json
Authorization: {{token}}

{
    "name": "bbbbbbbbbbbbbbb",
    "email": "aas1232sa@hsshh.com",
    "password": "12346123123",
    "phone": "12341231236",  
    "birth": "2001-11-11",
    "profile": "Cliente"
}

### Delete
DELETE {{URL}}/person/0b6f2aa9-6923-42bb-b3e7-e6e1b3b1095f
Authorization: {{token}}