@URL_BASE=http://localhost:8080

// ------------------ GET ------------------
###Obter todas as pessoas por pagina
GET {{URL_BASE}}/pessoa/pages?size=20&page=2&sort=email&direction=DESC

###Obter todas as pessoas
GET {{URL_BASE}}/pessoa

###Obter pessoa pelo ID
GET {{URL_BASE}}/pessoa/10


// ------------------ PUT ------------------




// ------------------ POST ------------------
###Cadastrar uma pessoa
POST {{URL_BASE}}/pessoa
Content-Type: application/json

{
    "nome": "Zé Ramalho",
    "email" : "zeramalho@gmail.coma",
    "senha": "misteriosDaMeiaNoite",
    "telefone": "+55 045 9 9912-3456",
    "nascimento" : "1960-01-01T00:00",
    "perfil" : "Cliente"
}




// ------------------ DELETE ------------------