@URL_BASE=http://localhost:8080
### create
POST {{URL_BASE}}/reserva
Content-Type: application/json

{
    "dataReserva": "3333-01-01"
}
### getAll
GET {{URL_BASE}}/reserva
### getById
GET {{URL_BASE}}/reserva/25fbcaaf-1b82-4b09-9c62-29b9bca76702
###
PUT {{URL_BASE}}/reserva/25fbcaaf-1b82-4b09-9c62-29b9bca76702
Content-Type: application/json

{
    "dataReserva": "2024-02-01"
}
###
DELETE {{URL_BASE}}/reserva/25fbcaaf-1b82-4b09-9c62-29b9bca76702